[package]
name = "spirit-hyper"
version = "0.5.2"
authors = ["Michal 'vorner' Vaner <vorner@vorner.cz>"]
description = "Hyper helpers for Spirit"
documentation = "https://docs.rs/spirit-hyper"
repository = "https://github.com/vorner/spirit"
categories = ["config", "web-programming"]
keywords = ["http", "hyper", "service", "configuration", "spirit"]
license = "Apache-2.0 OR MIT"
readme = "README.md"
edition = "2018"
include = [
    "Cargo.toml",
    "README.md",
    "src/**",
]

[badges]
travis-ci = { repository = "vorner/spirit" }
maintenance = { status = "actively-developed" }

[features]
default = ["cfg-help"]
cfg-help = ["spirit/cfg-help", "spirit-tokio/cfg-help", "structdoc"]

[dependencies]
failure = "~0.1"
futures = "~0.1"
hyper = "~0.12.17"
log = "~0.4"
serde = { version = "~1", features = ["derive"] }
serde_derive = "~1"
spirit = { path = "..", version = "~0.3.3", default-features = false }
spirit-tokio = { path = "../spirit-tokio", version = "~0.5", default-features = false }
structdoc = { version = "~0.1", optional = true }
structopt = "~0.3"
tokio = "~0.1"

[dev-dependencies]
env_logger = "~0.6"
version-sync = "~0.8"
