[package]
name = "spirit-hyper"
version = "0.4.0"
authors = ["Michal 'vorner' Vaner <vorner@vorner.cz>"]
description = "Hyper helpers for Spirit"
documentation = "https://docs.rs/spirit-hyper"
repository = "https://github.com/vorner/spirit"
keywords = ["http", "hyper", "service", "configuration", "spirit"]
license = "Apache-2.0/MIT"
readme = "README.md"

[badges]
travis-ci = { repository = "vorner/spirit" }
maintenance = { status = "actively-developed" }

[dependencies]
arc-swap = "~0.3"
failure = "~0.1"
futures = "~0.1"
hyper = "~0.12.16"
log = "~0.4"
serde = "~1"
serde_derive = "~1"
spirit = { path = "..", version = "~0.2" }
spirit-tokio = { path = "../spirit-tokio", version = "~0.4", default-features = false }
structopt = "~0.2"
tokio = "~0.1"

[dev-dependencies]
env_logger = "~0.6"
version-sync = "~0.6"
