[package]
name = "tutopoc"
version = "0.1.0"
authors = ["Michal 'vorner' Vaner <vorner@vorner.cz>"]
edition = "2018"

[dependencies]
hyper = "~0.12"
http = "~0.1"
serde = { version = "~1", features = ["derive"] }
serde_json = "~1"
