[package]
name = "spirit"
version = "0.1.0"
authors = ["Michal 'vorner' Vaner <vorner@vorner.cz>"]
description = "Helper to create well behaved daemons"
documentation = "https://docs.rs/spirit"
repository = "https://github.com/vorner/spirit"
# TODO
readme = "README.md"
keywords = ["unix", "daemon", "service"]
license = "Apache-2.0/MIT"

[badges]
travis-ci = { repository = "vorner/spirit" }
maintenance = { status = "actively-developed" }

[dependencies]
arc-swap = "~0.3"
chrono = "~0.4"
config = "~0.9"
daemonize = { git = "https://github.com/vorner/daemonize", branch = "foreground" }
failure = "~0.1"
fallible-iterator = "~0.1"
fern = { version = "~0.5", features = ["syslog-4"] }
itertools = "~0.7"
libc = "~0.2"
log = "~0.4"
log-panics = "~2"
log-reroute = "~0.1"
parking_lot = "~0.6"
serde = "~1"
serde_derive = "~1"
signal-hook = "~0.1"
structopt = "~0.2"
syslog = "~4"

[dev-dependencies]
futures = "~0.1"
lazy_static = "~1"
tokio = "~0.1"
version-sync = "~0.5"
