[package]
name = "spirit"
version = "0.2.8"
authors = ["Michal 'vorner' Vaner <vorner@vorner.cz>"]
description = "Helper to create well behaved daemons with runtime-reconfiguration support"
documentation = "https://docs.rs/spirit"
repository = "https://github.com/vorner/spirit"
readme = "README.md"
keywords = ["unix", "daemon", "service", "configuration"]
license = "Apache-2.0/MIT"

[workspace]
members = [
    "./",
    "spirit-daemonize",
    "spirit-hyper",
    "spirit-log",
    "spirit-reqwest",
    "spirit-tokio",
    "examples/hws-complete",
]

[badges]
travis-ci = { repository = "vorner/spirit" }
maintenance = { status = "actively-developed" }

[features]
ini = ["config/ini"]
json = ["config/json"]
hjson = ["config/hjson"]
yaml = ["config/yaml"]

[dependencies]
arc-swap = "~0.3"
config = { version = "~0.9", default-features = false, features = ["toml"] }
failure = "~0.1"
fallible-iterator = "~0.1"
itertools = "~0.7"
libc = "~0.2"
log = "~0.4"
parking_lot = "~0.6"
serde = "~1"
serde_derive = "~1"
signal-hook = "~0.1"
structopt = "~0.2"

[dev-dependencies]
lazy_static = "~1"
version-sync = "~0.6"
