[package]
name = "spirit-tokio"
version = "0.3.1"
authors = ["Michal 'vorner' Vaner <vorner@vorner.cz>"]
description = "Tokio helpers for Spirit"
documentation = "https://docs.rs/spirit-tokio"
repository = "https://github.com/vorner/spirit"
license = "Apache-2.0/MIT"
readme = "README.md"

[features]

[badges]
travis-ci = { repository = "vorner/spirit" }
maintenance = { status = "actively-developed" }

[dependencies]
either = { version = "~1", optional = true }
failure = "~0.1"
futures = "~0.1"
log = "~0.4"
net2 = "~0.2"
parking_lot = "~0.6"
serde = "~1"
serde_derive = "~1"
serde-humanize-rs = "~0.1"
spirit = { version = "~0.2", path = "..", default-features = false }
structopt = "~0.2"
tk-listen = "~0.2"
tokio = "~0.1.8"

[dev-dependencies]
env_logger = "~0.6"
serde_json = "~1"
version-sync = "~0.5"
