[package]
name = "spirit-log"
version = "0.1.5"
authors = ["Michal 'vorner' Vaner <vorner@vorner.cz>"]
description = "Spirit helpers and config fragments for logging"
documentation = "https://docs.rs/spirit-log"
repository = "https://github.com/vorner/spirit"
readme = "README.md"
keywords = ["log", "spirit", "service", "configuration"]
license = "Apache-2.0/MIT"

[badges]
travis-ci = { repository = "vorner/spirit" }
maintenance = { status = "actively-developed" }

[features]
default = ["with-backtrace", "cfg-help"]
with-backtrace = ["log-panics/with-backtrace"]
cfg-help = ["spirit/cfg-help", "structdoc"]

[dependencies]
chrono = "~0.4"
failure = "~0.1"
fern = { version = "~0.5", features = ["syslog-4"] }
itertools = "~0.7"
log = "~0.4"
log-panics = "~2"
log-reroute = "~0.1"
serde = "~1"
serde_derive = "~1"
serde_json = "~1"
spirit = { version = "~0.2", path = "..", default-features = false }
structdoc = { version = "~0.1", optional = true }
structopt = "~0.2"
syslog = "~4"

[dev-dependencies]
version-sync = "~0.6"
