[[listen]]
port = 1234
scale = 2

[[listen]]
port = 5678
host = "localhost"

[ui]
msg = "Hello world"

[[logging]]
level = "INFO"
type = "stderr"

[[logging]]
level = "DEBUG"
type = "file"
filename = "/tmp/hws.log"
